baseURL = "https://amplifytechwi.com/"
languageCode = "en-us"
title = "Amplify Technologies"
enableRobotsTXT = true
disableAliases = true
# post pagination
paginate = "6"
summaryLength = 30

#################### default parameters ################################

[params]
  logo = "images/logo.jpg"
  # Meta data
  description = " "
  author = "Amplify Technologies"
  # Contact Information
  phone = "920-759-9315"
  email = "allie@randrtech.com"
  address = """
    PO Box 1007,
    Kaukauna, WI 54310"""
  hoursMF = "Monday-Friday 9 am - 4 pm"
  hoursSat = "Saturdays 9 am - 1 pm"
  hoursSun = "Closed Sunday"
  disallowSearchEngines = true
  # Google Analitycs
  googleAnalytics = " " # Your ID# search 
  minifyBundles = true

# add redirects/headers
  [outputs]
  home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
  suffixes = [""]
  delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
  mediatype = "text/netlify"
  baseName = "_redirects"
  isPlainText = true
  notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
  mediatype = "text/netlify"
  baseName = "_headers"
  isPlainText = true
  notAlternative = true

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[markup.goldmark.renderer]
  unsafe= true

[[menu.main]]
    name = "Services"
    url  = "/services/"
    weight = 2

  [[menu.main]]
    parent = "Services"
    name = "Commercial Grade Speakers, Paging & Emergency"
    weight = 1
    url = "/services/commercial-speakers-pagers-emergency/"

  [[menu.main]]
    parent = "Services"
    name = "Audiovisual and Lighting Control"
    weight = 2
    url = "/services/audiovisual-lighting-controls/"

  [[menu.main]]
    parent = "Services"
    name = "Commercial Grade Cameras"
    weight = 3
    url = "/services/commercial-grade-cameras/"

  [[menu.main]]
    parent = "Services"
    name = "Audiovisual and Lighting Control"
    weight = 4
    url = "/services/audiovisual-lighting-controls/"

  [[menu.main]]
    parent = "Services"
    name = "Access Control Systems"
    weight = 5
    url = "/services/access-control-systems/"

  [[menu.main]]
    parent = "Services"
    name = "Surveillance Systems"
    weight = 6
    url = "/services/surveillance-systems/"

  [[menu.main]]
    parent = "Services"
    name = "DirecTV Installation & Service"
    weight = 7
    url = "/services/directv-install-service/"

[[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 4

[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 6