backend:
  branch: main
  name: git-gateway
  repo: insight-creative/amplify-tech

media_folder: "site/static/images/blog" # Folder where user uploaded files should go
public_folder: "images"

collections: # A list of collections the CMS should be able to edit
  - name: "tech-tips" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Tech Tips" # Used in the UI, ie.: "New Post"
    folder: "content/tech-tips" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Categories",
          name: "categories",
          widget: "select",
          multiple: true,
          options: ["Surveillance Systems", "DirecTV Install & Service"],
        }
      - {
          label: "Featured Image",
          name: "image",
          widget: "image",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
